- name: Remove All Desktop from CentOS
  hosts: all
  become_user:
  tasks:
    - name: This command will remove the X Window and Gnome
      shell:
        cmd: sudo yum groupremove 'X Window System' 'GNOME' 'gnome-classic-session' 'gnome-terminal' 'nautilus-open-terminal' 'control-center liberation-mono-fonts'
    
    - name: This command will remove Gnome Desktop Group
      shell:
        cmd: sudo yum groupremove "GNOME Desktop"
    
    - name: This command will remove the MATE Desktop Group
      shell:
        cmd: sudo yum groupremove -y "MATE Desktop"
    
    - name: This command will remove xorg
      shell:
        cmd: sudo yum remove xorg* -y
    
    - name: This command will remove gnome
      shell:
        cmd: sudo yum remove gnome* -y
    
    - name: This command will run autoremove
      shell:
        cmd: sudo yum autoremove -y
    
    - name: Rebooting everything!
      reboot:
      
