- name: Yum Update All
  hosts: all
  become_user:
  tasks:
  
    - name: upgrade all packages, excluding kernel & foo related packages
      yum:
         name: '*'
         state: latest
         exclude: kernel*,foo*
    - name: Remove the 'Gnome desktop' environment group
      yum:
        name: "@^gnome-desktop-environment"
        state: present
        
