- name: Yum Update All
  hosts: all
  tasks:
  
    - name: upgrade all packages, excluding kernel & foo related packages
      yum:
         name: '*'
         state: latest
         exclude: kernel*,foo*
