## File: yum_update.yml
## By: Challon Holt 06/20/20
## Purpose: Update all systems
- name: Yum Update All
  hosts: all
  gather_facts: yes
  become_user:
  tasks:
    
    - name: Distribution
      debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version}} {{ ansible_distribution_major_version }}"
    
    - name: upgrade all packages, excluding kernel & foo related packages
      yum:
        name: '*'
        state: latest
        exclude: kernel*,foo*
